### PR TITLE
travis

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by samandmoore** [comment]
Does the one test actually work for you given the current configuration? I was having issues with jsdom and was thinking of switching to karma with phantomjs. 

I'm running on node and not on iojs if that might make any difference.

**Comment by samccone** [comment]
you are using jsdom 4.0.0 which is only io compat. If you want to use nodejs you will want to go to the 3.x version of jsdom.

The one test does pass ;) if you enable this repo on travis your builds will start passing

**Comment by samccone** [comment]
screen shot 2015-02-23 at 10 16 57 pm

**Comment by samandmoore** [comment]
Excellent.

**Comment by samandmoore** [comment]
awesome. lgtm.

**Comment by samccone** [comment]
:heart:

**Pull request merged**
