### PR TITLE
Update Marionette Version & Lock Untrusted

### PR DESCRIPTION
**Pull request by samccone**
welcome to the future :+1:

### CODE REVIEW

**Comment by jamesplease** [comment]
@samccone, should this library not support the broadest range of versions as possible? There's no feature specific to 2.4 that this library **requires**, so why limit who can use the library?

If I had to guess, `^2.0.0` is what this lib should support. If the dep is changed, Travis CI should be added + configured to test against multiple versions of the lib.

**Comment by samccone** [comment]
@jmeas you are correct I have updated the PR

I have also locked backbone and underscore, because they are not to be trusted, thanks for the eyes.

**Comment by samandmoore** [comment]
No reason to limit to only the latest versions.

lgtm. Thanks for the quick contribution.

**Comment by samccone** [comment]
ah hold one moment

**Comment by samccone** [comment]
kk, we introduced object in 2.1 :)

**Comment by samandmoore** [comment]
Good catch.

**Pull request merged**
